#!/usr/bin/env python3
"""Build native VERA tiles from drawing primitives, never from the reference PNG."""
from pathlib import Path
import json, math, struct
from PIL import Image, ImageDraw
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'dist/sdcard'
OUT.mkdir(parents=True, exist_ok=True)
for name,source in [('WCRDEMO','demo-us'),('WCRDPH','demo-ph')]:
 (OUT/(name+'.BIN')).write_bytes((ROOT/'assets/radar'/(source+'.bin')).read_bytes())
# Index zero is transparent. Index one is opaque black.
COLORS = ['000000','000000','000088','0011bb','22ccee','ffff55','eeeeff','22aa22',
          '66cc33','aadd88','9999cc','9955dd','dd22aa','ff8833','119922','ffffff']
RGB = [tuple(int(c[i:i+2],16) for i in (0,2,4)) for c in COLORS]
BRAND_RGB = RGB.copy()
BRAND_RGB[14]=(136,136,136)
BRAND_RGB[6]=(221,204,187)
BRAND_RGB[15]=(204,34,34)

def graphic(path, size, colors=RGB, background=1):
 """Compile a standalone RGBA asset into the fixed X16 palette."""
 source=Image.open(ROOT/path).convert('RGBA').resize(size,Image.Resampling.LANCZOS)
 result=Image.new('P',size,background)
 for y in range(size[1]):
  for x in range(size[0]):
   r,g,b,a=source.getpixel((x,y))
   if a>=128:
    result.putpixel((x,y),min(range(1,16),key=lambda i:sum((c-v)**2 for c,v in zip(colors[i],(r,g,b)))))
 return result

from scenery import scene, THEMES

def station_scene(phase,theme=0):
 return scene(phase,theme,text)
# Public 5x7 cell shapes; one row per line, packed into five vertical columns.
LETTERS = ['7e1111117e','7f49494936','3e41414122','7f4141221c','7f49494941','7f09090901',
'3e41495132','7f0808087f','00417f4100','2040413f01','7f08142241','7f40404040',
'7f020c027f','7f0408107f','3e4141413e','7f09090906','3e4151215e','7f09192946',
'4649494931','01017f0101','3f4040403f','1f2040201f','3f4038403f','6314081463',
'0708700807','6151494543']
DIGITS=['3e5149453e','00427f4000','4261514946','2141454b31','1814127f10',
'2745454539','3c4a494930','0171090503','3649494936','064949291e']
GLYPHS={ord(c): bytes.fromhex(g) for c,g in zip('ABCDEFGHIJKLMNOPQRSTUVWXYZ',LETTERS)}
GLYPHS.update({ord(c):bytes.fromhex(g) for c,g in zip('0123456789',DIGITS)})
GLYPHS.update({ord(c):bytes.fromhex(g) for c,g in {
' ':'0000000000',':':'0036360000','.':'0060600000',',':'0040200000','-':'0808080808',
'/':'2010080402','%':'2313086462','+':'08083e0808','>':'0041221408','<':'0814224100',
'!':'00005f0000','?':'0201510906',"'":'0000030000','(':'001c224100',')':'0041221c00',
'=':'1414141414','[':'007f414100',']':'0041417f00','*':'14083e0814','_':'4040404040',
'|':'00007f0000'}.items()})
GLYPHS.update({ord(c.lower()):GLYPHS[ord(c)] for c in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'})
GLYPHS[127]=bytes.fromhex('0609090600')
banner_columns=[v for code in range(32,96) for v in GLYPHS.get(code,GLYPHS[32])]
(ROOT/'src/banner_font.p8').write_text('; Generated by tools/build_assets.py from the shared 5x7 font.\n'
 +'banner_font {\n    ubyte[256] columns = '+str(banner_columns[:256])+'\n    ubyte[64] more = '+str(banner_columns[256:])+'\n}\n')

def text(im,x,y,s,color=6,scale=1):
 d=ImageDraw.Draw(im)
 for c in s.upper():
  for col,bits in enumerate(GLYPHS.get(ord(c),GLYPHS[ord('?')])):
   for row in range(7):
    if bits & (1<<row):d.rectangle((x+col*scale,y+row*scale,x+(col+1)*scale-1,y+(row+1)*scale-1),fill=color)
  x+=6*scale

def frame(d,box):
 x,y,r,b=box;d.rectangle(box,fill=1,outline=4,width=2)
 d.line((x+3,b-2,r-2,b-2),fill=2);d.line((r-2,y+3,r-2,b-2),fill=2)
 d.line((x+3,y+3,r-3,y+3),fill=10)

def cloud(d,x,y,rain=False):
 d.ellipse((x+4,y-6,x+16,y+6),fill=6);d.ellipse((x-2,y,x+11,y+9),fill=6)
 d.ellipse((x+10,y,x+23,y+9),fill=15);d.line((x,y+10,x+22,y+10),fill=10,width=2)
 if rain:
  for a in (2,10,18):d.line((x+a,y+13,x+a-3,y+19),fill=4,width=2)
def sun(d,x,y):
 for a in range(0,360,45):
  r=math.radians(a);d.line((x+int(10*math.cos(r)),y+int(10*math.sin(r)),x+int(14*math.cos(r)),y+int(14*math.sin(r))),fill=5,width=2)
 d.ellipse((x-8,y-8,x+8,y+8),fill=5,outline=13,width=2)
def moon(d,x,y):
 d.ellipse((x,y,x+26,y+30),fill=6);d.ellipse((x+10,y-3,x+31,y+24),fill=1)

def geo_polygons():
 t=json.loads((ROOT/'assets/data/states-albers-10m.json').read_text());sx,sy=t['transform']['scale'];tx,ty=t['transform']['translate']; arcs=[]
 for arc in t['arcs']:
  x=y=0; pts=[]
  for dx,dy in arc:x+=dx;y+=dy;pts.append((x*sx+tx,y*sy+ty))
  arcs.append(pts)
 result=[]
 for g in t['objects']['states']['geometries']:
  if int(g['id']) in (2,15,72):continue
  polys=g['arcs'] if g['type']=='MultiPolygon' else [g['arcs']]
  for polygon in polys:
   points=[]
   for idx in polygon[0]:points.extend(arcs[idx] if idx>=0 else arcs[~idx][::-1])
   result.append(points)
 return result
POLYGONS=geo_polygons()
xs=[p[0] for poly in POLYGONS for p in poly];ys=[p[1] for poly in POLYGONS for p in poly]
BOUNDS=(min(xs),min(ys),max(xs),max(ys))
def mapart(regional=False,radar=False):
 im=Image.new('P',(352,256),3);d=ImageDraw.Draw(im)
 for y in range(0,256,2):d.line((0,y,351,y),fill=2)
 x0,y0,x1,y1=BOUNDS
 for poly in POLYGONS:
  pts=[(int((x-x0)/(x1-x0)*324)+14,int((y-y0)/(y1-y0)*206)+18) for x,y in poly]
  if regional:pts=[((x-218)*3+176,(y-93)*3+115) for x,y in pts]
  d.polygon(pts,fill=7);d.line(pts,fill=9,width=1)
 # Alternate green scanlines without repainting the crisp state borders.
 for y in range(1,256,2):
  for x in range(352):
   if im.getpixel((x,y))==7:im.putpixel((x,y),14)
 return im

def base():
 im=Image.new('P',(640,480),1);d=ImageDraw.Draw(im)
 frame(d,(2,2,637,55));d.rectangle((5,5,634,44),fill=2)
 for y,c in [(44,12),(46,11),(48,13),(50,5),(52,4)]:d.line((5,y,634,y),fill=c,width=2)
 im.paste(graphic('assets/branding/roddy-badge.png',(48,26),BRAND_RGB,2),(8,11))
 text(im,72,9,'WEATHER COMMANDER',6,2)
 d.line((342,9,342,38),fill=3)
 d.line((344,9,344,38),fill=4)
 frame(d,(3,63,132,334));frame(d,(136,63,486,334));frame(d,(490,63,637,334))
 d.rectangle((139,67,482,84),fill=2);d.line((140,85,482,85),fill=10)
 im.paste(mapart(),(136,80)) # edges restored below; actual center viewport x136 y80 352x256
 frame_center=ImageDraw.Draw(im);frame_center.rectangle((136,63,486,334),outline=4,width=2)
 frame_center.rectangle((139,67,483,85),fill=2);frame_center.line((140,86,482,86),fill=10)
 # Sidebar pictograms, rendered independently of labels/highlight.
 # Destination board: two selectable rows and an arrow, distinct from maps.
 d.rectangle((12,83,30,99),fill=2,outline=4)
 d.line((14,85,28,85),fill=6)
 d.polygon([(14,89),(17,91),(14,93)],fill=5)
 d.line((20,90,27,90),fill=5)
 d.line((20,92,25,92),fill=5)
 d.line((15,96,27,96),fill=4)
 x0,y0,x1,y1=BOUNDS
 for poly in POLYGONS:
  d.polygon([(14+int((x-x0)/(x1-x0)*17),106+int((y-y0)/(y1-y0)*12)) for x,y in poly],fill=4)
 d.ellipse((14,129,29,144),outline=4)
 d.ellipse((18,129,25,144),outline=4)
 d.line((14,134,29,134),fill=4);d.line((14,139,29,139),fill=4)
 for x,y in [(14,159),(19,154),(24,157),(28,160)]:d.rectangle((x,y,x+2,168),fill=4)
 for radius in (4,8,11):d.arc((21-radius,185-radius,21+radius,185+radius),40,320,fill=4)
 d.ellipse((20,184,22,186),fill=4)
 d.rectangle((14,201,29,215),outline=4)
 for y in (205,209,213):d.line((16,y,27,y),fill=4)
 d.line((18,201,18,215),fill=4)
 d.rectangle((14,225,29,239),outline=4)
 for y in (228,233,237):d.point((17,y),fill=4);d.line((21,y,27,y),fill=4)
 d.ellipse((15,250,28,263),fill=4)
 for angle in range(0,360,45):
  r=math.radians(angle);x=21+int(8*math.cos(r));y=256+int(8*math.sin(r));d.rectangle((x-1,y-1,x+2,y+2),fill=4)
 d.ellipse((19,254,24,259),fill=1)
 d.ellipse((14,273,29,288),fill=10)
 text(im,19,277,'I',1)
 im.paste(graphic('assets/graphics/satellite-dish.png',(40,40)),(7,294))
 text(im,48,301,'YOUR WEATHER',4)
 text(im,48,313,'DAY AND NIGHT',6)
 # The right panel owns its section dividers; no shell lines behind its icons.
 # City table and station ident
 frame(d,(3,336,637,432));d.line((477,340,477,429),fill=10,width=2)
 d.line((10,351,468,351),fill=10);d.line((244,357,244,424),fill=10)
 # The station application owns x480..631,y344..423, inside this shell frame.
 d.rectangle((480,340,633,426),fill=2)
 frame(d,(3,433,637,451));d.rectangle((5,435,634,449),fill=2)
 d.line((4,454,637,454),fill=10)
 return im

im=base()
# A single atlas serves all panel backgrounds. Each visible cell is an actual 8x8 tile.
variants={'NAT':im.crop((136,88,488,328)),'REG':mapart().crop((0,8,352,248)),
          'RAD':im.crop((136,88,488,328)),'BLK':Image.new('P',(352,240),2)}
tiles=[];index={}
def tile_id(tile):
 raw=bytes(tile.getdata())
 if raw not in index:
  idx=len(tiles);tiles.append(raw);index[raw]=idx
  for method,flag in [(Image.Transpose.FLIP_LEFT_RIGHT,1024),(Image.Transpose.FLIP_TOP_BOTTOM,2048),(Image.Transpose.ROTATE_180,3072)]:
   index.setdefault(bytes(tile.transpose(method).getdata()),idx|flag)
 return index[raw]
def encode_map(pic,width=128,height=64,palette_bank=0):
 result=bytearray(width*height*2)
 for y in range(pic.height//8):
  for x in range(pic.width//8):
   idx=tile_id(pic.crop((x*8,y*8,x*8+8,y*8+8)))
   off=(y*width+x)*2;result[off:off+2]=struct.pack('<H',idx | palette_bank<<12)
 return result
base_map=encode_map(im)
for y in range(1,5):
 for x in range(1,7):base_map[(y*128+x)*2+1] |= 0xa0
(OUT/'WCMAP.BIN').write_bytes(base_map)
for name,pic in variants.items():(OUT/f'WC{name}.BIN').write_bytes(encode_map(pic,44,30,15 if name=='RAD' else 0))
scenes=[station_scene(phase,theme) for theme in range(len(THEMES)) for phase in range(4)]
for number,pic in enumerate(scenes):
 raw=b''.join(bytes(pic.crop((x,y,x+8,y+8)).getdata()) for y in range(0,80,8) for x in range(0,152,8))
 (OUT/f'WCSC{number:02}.BIN').write_bytes(bytes((raw[i]<<4)|raw[i+1] for i in range(0,len(raw),2)))
assert len(tiles)<=628, f'{len(tiles)} static tiles overlaps header reservation'
packed=bytes((t[i]<<4)|t[i+1] for t in tiles for i in range(0,64,2))
(OUT/'WCTILES.BIN').write_bytes(packed)
palette=list(RGB)
for fg,bg in [(4,1),(5,1),(6,1),(4,2),(5,2),(6,2),(1,5),(1,14),(1,4)]:
 palette.extend([RGB[0],RGB[fg],(136,136,136) if bg==14 else RGB[bg]]+[RGB[0]]*13)
palette.extend(BRAND_RGB)
station_palettes=[]
for phase,values in enumerate([
 ['332277','995588','221155','ffdd88','ffffbb','ee9988','223344','557766','ddbb99','776688'],
 ['1155aa','4488cc','113366','ffff99','ffffcc','99ccdd','225544','55aa77','eedd99','668899'],
 ['221166','773388','110033','ffdd66','ffcc77','ee7777','222244','665566','cc9977','775588'],
 ['000066','2222aa','000022','ffff77','ffffaa','773388','111133','224455','8888bb','333388']]):
 colors=RGB.copy()
 for idx,value in zip((3,11,2,5,15,10,7,8,9,14),values):colors[idx]=tuple(bytes.fromhex(value))
 if phase==3:colors[13]=(204,85,102)
 palette.extend(colors);station_palettes.append(colors)
# Palette 15: blue ocean, green terrain, mint coasts; stronger radar echoes.
radar_colors=RGB.copy()
for idx,value in {1:'000011',2:'000066',3:'001188',7:'118833',14:'117733',9:'aadd99',4:'3388bb',8:'33cc55',5:'ffff33',13:'ff8822',12:'ee2233',11:'cc44dd',15:'ffffff'}.items():radar_colors[idx]=tuple(bytes.fromhex(value))
palette.extend(radar_colors)
(OUT/'WCPAL.BIN').write_bytes(bytes(v for r,g,b in palette for v in (((g//17)<<4)|(b//17),r//17)))
font=bytearray(256*8)
for code,cols in GLYPHS.items():
 for y in range(7):font[code*8+y]=sum((1<<(6-x)) for x,b in enumerate(cols) if b&(1<<y))
# Two-by-three text cells per large numeral (10x21 pixels).
for n,c in enumerate('0123456789'):
 glyph=Image.new('1',(16,24));dd=ImageDraw.Draw(glyph)
 for x,bits in enumerate(GLYPHS[ord(c)]):
  for y in range(7):
   if bits&(1<<y):dd.rectangle((2+x*2,1+y*3,3+x*2,3+y*3),fill=1)
 for q in range(6):
  tile=glyph.crop(((q%2)*8,(q//2)*8,(q%2)*8+8,(q//2)*8+8))
  for y in range(8):font[(128+n*6+q)*8+y]=sum(tile.getpixel((x,y))<<(7-x) for x in range(8))
# 4x4 mono icons at 192=moon, 208=sun, 224=cloud, 240=rain.
for n in range(4):
 icon=Image.new('P',(32,32),1);dd=ImageDraw.Draw(icon)
 if n==0:moon(dd,2,1)
 elif n==1:sun(dd,16,16)
 else:cloud(dd,5,12,n==3)
 for q in range(16):
  for y in range(8):font[(192+n*16+q)*8+y]=sum((1 if icon.getpixel(((q%4)*8+x,(q//4)*8+y)) not in (0,1) else 0)<<(7-x) for x in range(8))
glyph_tiles=bytearray()
for row_number,bits in enumerate(font):
 for shift in (6,4,2,0):
  left=1 if bits&(1<<(shift+1)) else (0 if row_number//8>=192 else 2)
  right=1 if bits&(1<<shift) else (0 if row_number//8>=192 else 2)
  glyph_tiles.append((left<<4)|right)
# Full-color National symbols are enlarged to 24px and packed after country art.
# Reuse control glyphs first, then free atlas space; printable text stays intact.
map_symbols=[]
for kind in range(7):
 icon=Image.new('P',(16,16),0);dd=ImageDraw.Draw(icon)
 if kind==0:
  dd.ellipse((3,1,13,12),fill=1);dd.ellipse((4,2,12,11),fill=5)
  dd.ellipse((7,0,15,8),fill=0);dd.point((3,14),fill=6)
 elif kind==1:
  for a in range(0,360,45):
   r=math.radians(a)
   dd.line((8+round(5*math.cos(r)),8+round(5*math.sin(r)),8+round(7*math.cos(r)),8+round(7*math.sin(r))),fill=13,width=2)
  dd.ellipse((3,3,12,12),fill=1);dd.ellipse((4,4,11,11),fill=13);dd.ellipse((5,4,10,10),fill=5)
 else:
  if kind==6:
   for y,x in [(4,3),(7,1),(10,4),(13,2)]:
    dd.line((x,y,14,y),fill=1,width=2);dd.line((x,y,13,y),fill=6)
  else:
   dd.polygon([(1,6),(3,4),(6,4),(6,2),(9,1),(12,3),(12,5),(14,6),(15,9),(13,11),(2,11),(0,9)],fill=1)
   dd.polygon([(2,6),(4,5),(7,5),(7,3),(9,2),(11,4),(11,6),(13,6),(14,9),(12,10),(2,10),(1,8)],fill=10)
   dd.polygon([(2,6),(4,5),(7,5),(7,3),(9,2),(11,4),(11,6),(13,7),(12,8),(2,8)],fill=15)
   if kind==3:
    for x in (3,7,11):dd.line((x,12,x-1,15),fill=4)
   elif kind==4:
    for x in (3,8,13):dd.line((x-1,13,x+1,13),fill=6);dd.line((x,12,x,14),fill=6)
   elif kind==5:dd.polygon([(8,9),(12,9),(9,12),(11,12),(6,15),(7,12),(5,12)],fill=5)
 map_symbols.append(icon.resize((24,24),Image.Resampling.NEAREST))
glyph_tiles.extend(bytes(32))  # transparent tile 256
# 257..463: streamed NOAA radar. 464..511: snow, storm, fog glyphs.
glyph_tiles.extend(bytes((512-257)*32))
# Half-cell edges center a 16-pixel navigation pill on its seven-pixel label.
glyph_tiles[188*32:189*32]=bytes(16)+bytes([0x22])*16
glyph_tiles[189*32:190*32]=bytes([0x22])*16+bytes(16)
for n in range(3):
 icon=Image.new('1',(32,32));dd=ImageDraw.Draw(icon)
 if n==0:
  for x,y in [(8,9),(23,9),(16,24)]:
   dd.line((x-5,y,x+5,y),fill=1);dd.line((x,y-5,x,y+5),fill=1)
   dd.line((x-3,y-3,x+3,y+3),fill=1);dd.line((x+3,y-3,x-3,y+3),fill=1)
 elif n==1:
  dd.ellipse((3,4,22,16),fill=1);dd.ellipse((12,8,28,18),fill=1)
  dd.polygon([(16,15),(25,15),(18,22),(23,22),(10,31),(14,23),(9,23)],fill=1)
 else:
  for y,x in [(7,4),(12,1),(17,6),(22,2),(27,8)]:dd.line((x,y,29,y),fill=1,width=2)
 for q in range(16):
  tile=icon.crop(((q%4)*8,(q//4)*8,(q%4)*8+8,(q//4)*8+8))
  data=bytes((tile.getpixel((x,y))<<4)|tile.getpixel((x+1,y)) for y in range(8) for x in range(0,8,2))
  offset=(464+n*16+q)*32;glyph_tiles[offset:offset+32]=data
# Paired glyphs 512..703 center seven-pixel text within a 16-pixel row.
# Text map B lives at $1B000, clear of this expanded font atlas.
for code in range(32,128):
 rows=[0]*4+list(font[code*8:code*8+8])+[0]*4
 for bits in rows:
  for shift in (6,4,2,0):
   left=1 if bits&(1<<(shift+1)) else 2
   right=1 if bits&(1<<shift) else 2
   glyph_tiles.append((left<<4)|right)
from country_art import build as country_art
country_art(ROOT,OUT,glyph_tiles)
# Share empty/identical tiles across all seven symbols. Sparse glyph references
# let the icons use the remaining font space without displacing any text.
map_book={bytes(64):256};map_glyphs=[];map_count=0
for icon in map_symbols:
 for q in range(9):
  raw=bytes(icon.crop((q%3*8,q//3*8,q%3*8+8,q//3*8+8)).getdata())
  if raw not in map_book:
   tile=map_count if map_count<32 else len(glyph_tiles)//32
   data=bytes((raw[i]<<4)|raw[i+1] for i in range(0,64,2))
   if map_count<32:glyph_tiles[tile*32:(tile+1)*32]=data
   else:glyph_tiles.extend(data)
   map_book[raw]=tile;map_count+=1
  map_glyphs.append(map_book[raw])
assert len(glyph_tiles)<=1024*32, 'National weather icons exceed the font atlas'
(ROOT/'src/map_icons.p8').write_text('; Generated by tools/build_assets.py. Full-color 24px National symbols.\n'
 +'map_icons {\n    uword[63] glyphs = '+str(map_glyphs)+'\n}\n')
print(f'National symbols: {map_count} unique tiles; font atlas {len(glyph_tiles)//32}/1024')
(OUT/'WCFONT.BIN').write_bytes(glyph_tiles)
# ROM moves sprite zero; both custom shapes share the exact (0,0) click tip.
pointers=[]
for active in (False,True):
 pointer=Image.new('P',(32,32),0);d=ImageDraw.Draw(pointer)
 # Plain outlined arrow in both states; the ROM click tip remains at (0,7).
 d.polygon([(0,7),(0,22),(4,19),(7,24),(9,23),(6,18),(11,18)],fill=15,outline=1)
 pixels=bytes(pointer.getdata());pointers.extend((pixels[i]<<4)|pixels[i+1] for i in range(0,len(pixels),2))
(OUT/'WCPOINTER.BIN').write_bytes(bytes(pointers))
im.putpalette([v for rgb in RGB for v in rgb]+[0]*(768-48))
preview=im.convert('RGB')
logo=graphic('assets/branding/roddy-badge.png',(48,26),BRAND_RGB,2)
logo.putpalette([v for rgb in BRAND_RGB for v in rgb]+[0]*(768-48))
preview.paste(logo.convert('RGB'),(8,11))
for phase,pic in enumerate(scenes):
 pic.putpalette([v for rgb in station_palettes[phase%4] for v in rgb]+[0]*(768-48))
 pic.convert('RGB').save(ROOT/'build'/f'station-{phase}.png')
preview.paste(scenes[3].convert('RGB'),(480,344));preview.save(ROOT/'build/artwork.png')
manifest={'tiles':len(tiles),'tile_bytes':len(packed),'vram':{'art_tiles':[0,len(packed)],'art_map':[32768,49152],'text_map_a':[49152,65536],'text_map_b':[0x1b000,0x1f000],'font':[65536,65536+len(glyph_tiles)],'palette':[129536,129536+len(palette)*2]}}
manifest['vram']['scenery']=[0x6000,0x77c0]
manifest['vram']['header']=[0x4e80,0x6000]
manifest['vram']['pointer']=[0x18000,0x18400]
(ROOT/'build/assets.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(f'VERA artwork: {len(tiles)}/768 static tiles, 190 streamed scene tiles; 28 scenery banks; 640x480')
